export const ERROR_CODES = [
  "PROJECT_NOT_FOUND",
  "PROJECT_ARCHIVED",
  "PROJECT_HAS_CLAIMED_TASKS",
  "TASK_NOT_FOUND",
  "TASK_ALREADY_CLAIMED",
  "TASK_NOT_CLAIMED",
  "TASK_CLAIM_MISMATCH",
  "TASK_NOT_ACTIONABLE",
  "TASK_HAS_INCOMPLETE_ACCEPTANCE_CRITERIA",
  "TASK_HAS_ACTIVE_BLOCKERS",
  "TASK_HAS_MISSING_ACCEPTANCE_EVIDENCE",
  "BLOCKER_NOT_FOUND",
  "BLOCKER_ALREADY_RESOLVED",
  "DECISION_NOT_FOUND",
  "LINK_NOT_FOUND",
  "CONTEXT_VERSION_NOT_FOUND",
  "CONTEXT_VERSION_CONFLICT",
  "CONTEXT_TOO_LARGE",
  "REPOSITORY_NOT_FOUND",
  "REPOSITORY_ALREADY_ASSOCIATED",
  "REPOSITORY_PATH_INVALID",
  "REPOSITORY_PATH_UNAVAILABLE",
  "REPOSITORY_IN_USE",
  "EXECUTION_NOT_RUNNING",
  "EXECUTION_OWNERSHIP_MISMATCH",
  "EXECUTION_WORKTREE_NOT_BOUND",
  "GIT_PROVENANCE_MISMATCH",
  "DEPENDENCY_NOT_FOUND",
  "DEPENDENCY_SELF_REFERENCE",
  "DEPENDENCY_CROSS_PROJECT",
  "DEPENDENCY_CYCLE",
  "ACCEPTANCE_CRITERION_NOT_FOUND",
  "ACCEPTANCE_CRITERION_ALREADY_COMPLETE",
  "ACCEPTANCE_CRITERION_ALREADY_OPEN",
  "INVALID_STATUS_TRANSITION",
  "INVALID_BOOTSTRAP_REFERENCE",
  "INVALID_METADATA",
  "WORKSPACE_IMPORT_CONFLICT",
  "WORKSPACE_IMPORT_INVALID",
  "VALIDATION_ERROR",
  "INTERNAL_ERROR",
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

export type ErrorDetails = Record<string, unknown>;

export type ErrorBody = {
  error: {
    code: ErrorCode;
    message: string;
    details: ErrorDetails;
  };
};

/**
 * The single error type raised by core services. Every transport (REST, MCP, CLI)
 * translates this into its own representation while preserving `code`.
 */
export class AgentContinuityError extends Error {
  readonly code: ErrorCode;
  readonly details: ErrorDetails;

  constructor(code: ErrorCode, message: string, details: ErrorDetails = {}) {
    super(message);
    this.name = "AgentContinuityError";
    this.code = code;
    this.details = details;
  }

  toBody(): ErrorBody {
    return { error: { code: this.code, message: this.message, details: this.details } };
  }

  static is(value: unknown): value is AgentContinuityError {
    return value instanceof AgentContinuityError;
  }
}

const HTTP_STATUS_BY_CODE: Record<ErrorCode, number> = {
  PROJECT_NOT_FOUND: 404,
  PROJECT_ARCHIVED: 409,
  PROJECT_HAS_CLAIMED_TASKS: 409,
  TASK_NOT_FOUND: 404,
  TASK_ALREADY_CLAIMED: 409,
  TASK_NOT_CLAIMED: 409,
  TASK_CLAIM_MISMATCH: 409,
  TASK_NOT_ACTIONABLE: 409,
  TASK_HAS_INCOMPLETE_ACCEPTANCE_CRITERIA: 409,
  TASK_HAS_ACTIVE_BLOCKERS: 409,
  TASK_HAS_MISSING_ACCEPTANCE_EVIDENCE: 409,
  BLOCKER_NOT_FOUND: 404,
  BLOCKER_ALREADY_RESOLVED: 409,
  DECISION_NOT_FOUND: 404,
  LINK_NOT_FOUND: 404,
  CONTEXT_VERSION_NOT_FOUND: 404,
  CONTEXT_VERSION_CONFLICT: 409,
  CONTEXT_TOO_LARGE: 413,
  REPOSITORY_NOT_FOUND: 404,
  REPOSITORY_ALREADY_ASSOCIATED: 409,
  REPOSITORY_PATH_INVALID: 400,
  REPOSITORY_PATH_UNAVAILABLE: 422,
  REPOSITORY_IN_USE: 409,
  EXECUTION_NOT_RUNNING: 409,
  EXECUTION_OWNERSHIP_MISMATCH: 409,
  EXECUTION_WORKTREE_NOT_BOUND: 404,
  GIT_PROVENANCE_MISMATCH: 409,
  DEPENDENCY_NOT_FOUND: 404,
  DEPENDENCY_SELF_REFERENCE: 400,
  DEPENDENCY_CROSS_PROJECT: 400,
  DEPENDENCY_CYCLE: 409,
  ACCEPTANCE_CRITERION_NOT_FOUND: 404,
  ACCEPTANCE_CRITERION_ALREADY_COMPLETE: 409,
  ACCEPTANCE_CRITERION_ALREADY_OPEN: 409,
  INVALID_STATUS_TRANSITION: 409,
  INVALID_BOOTSTRAP_REFERENCE: 400,
  INVALID_METADATA: 400,
  WORKSPACE_IMPORT_CONFLICT: 409,
  WORKSPACE_IMPORT_INVALID: 400,
  VALIDATION_ERROR: 400,
  INTERNAL_ERROR: 500,
};

export function httpStatusForErrorCode(code: ErrorCode): number {
  return HTTP_STATUS_BY_CODE[code] ?? 500;
}
